services:
  timeplus:
    image: "d.timeplus.com/timeplus-io/proton:latest"
    container_name: "timeplus-connect-timeplus-server"
    ports:
      - "8463:8463"
      - "8123:8123"
      - "3218:3218"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - /mnt/timeplusd:/var/lib/timeplusd
